---
# build artifact on semaphore: config-<sha>.zip + manifest
- name: build artifacts (config-<sha>.zip + manifest)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    repo_root: "{{ playbook_dir | dirname }}"
    artifacts_dir: "/srv/mc/artifacts"
    commit_sha: "{{ lookup('pipe', 'git -C ' ~ repo_root ~ ' rev-parse HEAD') | trim }}"
    build_cfg: "{{ lookup('file', repo_root ~ '/.mc-build.yml') | from_yaml }}"
    triggers: "{{ build_cfg.triggers | default([]) }}"
    package_globs: "{{ build_cfg.package | default([]) }}"
    manifest_path: "{{ artifacts_dir }}/config-{{ commit_sha }}.json"
    zip_path: "{{ artifacts_dir }}/config-{{ commit_sha }}.zip"

  tasks:
    - name: ensure artifacts dir
      file: { path: "{{ artifacts_dir }}", state: directory, mode: "0755" }

    - name: get previous commit
      command: git -C "{{ repo_root }}" rev-parse HEAD~1
      register: prev
      changed_when: false
      failed_when: false

    - name: diff current vs previous commit
      command: git -C "{{ repo_root }}" diff --name-only {{ prev.stdout | default('HEAD') }} HEAD
      register: diff
      changed_when: false

    - name: check if relevant files changed
      set_fact:
        changed_relevant: "{{ (diff.stdout_lines | default([])) | select('match', item) | list | length > 0 }}"
      loop: "{{ triggers }}"
      register: match_results
      changed_when: false

    - name: skip build if nothing relevant changed
      when: match_results.results | map(attribute='ansible_facts.changed_relevant') | select('equalto', true) | list | length == 0
      debug: { msg: "no relevant changes, skipping build" }
    - meta: end_play
      when: match_results.results | map(attribute='ansible_facts.changed_relevant') | select('equalto', true) | list | length == 0

    - name: collect files to package (resolve globs)
      command: >
        bash -lc "shopt -s globstar dotglob nullglob;
        cd '{{ repo_root }}'; printf '%s\n' {{ package_globs | map('quote') | join(' ') }}"
      register: pkg_list
      changed_when: false

    - name: create zip archive
      archive:
        path: "{{ pkg_list.stdout_lines | map('regex_replace', '^(.*)$', repo_root ~ '/\\1') | list }}"
        dest: "{{ zip_path }}"
        format: zip
        remove: no

    - name: compute sha256
      command: sha256sum "{{ zip_path }}"
      register: sha
      changed_when: false

    - name: write manifest
      copy:
        dest: "{{ manifest_path }}"
        mode: "0644"
        content: |
          {
            "commit": "{{ commit_sha }}",
            "created_at": "{{ lookup('pipe','date -Iseconds') | trim }}",
            "zip": "{{ zip_path }}",
            "sha256": "{{ (sha.stdout.split()[0]) | default('') }}"
          }

    - name: update latest pointers
      copy: { dest: "{{ artifacts_dir }}/latest.txt", content: "{{ commit_sha }}\n", mode: "0644" }
    - file: { src: "{{ zip_path }}", dest: "{{ artifacts_dir }}/config-latest.zip", state: link, force: yes }

    - name: cleanup old artifacts (keep last 10)
      shell: |
        ls -1t {{ artifacts_dir }}/config-*.zip | tail -n +11 | xargs -r rm -f
        ls -1t {{ artifacts_dir }}/config-*.json | tail -n +11 | xargs -r rm -f
      changed_when: false