- name: deploy config
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false

#------------------------------------------#

  vars:
    target_dir: "/home/mc/minecraft-survival"
    service_name: "mc-survival-java"
    mc_port: 25565
    artifacts_dir: "/home/mc/artifact"
    set_motd_from_tag: true
    protect_paths:
      - "world*/"
      - "logs/"
      - "crash-reports/"
      - "backups/"
      - "cache/"
      - "debug/"
      - "rcon.pipe"
      - "usercache.json"
      - "banned-ips.json"
      - "banned-players.json"
      - "whitelist.json"
      - "ops.json"
      - "versions/"
      - "libraries/"
      - "plugins/*/data/**"
      - "plugins/*/cache/**"
      - "plugins/*/logs/**"
      - "plugins/*/storage/**"

#------------------------------------------#

  pre_tasks:
    - name: ensure target dir
      ansible.builtin.file:
        path: "{{ target_dir }}"
        state: directory
        owner: mc
        group: mc
        mode: "0755"

    - name: read latest tag file
      ansible.builtin.slurp:
        src: "{{ artifacts_dir }}/latest.txt"
      register: latest_tag_file
      failed_when: latest_tag_file is failed or latest_tag_file.content is not defined

    - name: set deploy tag and stage dir
      ansible.builtin.set_fact:
        deploy_tag: "{{ (latest_tag_file.content | b64decode).strip() }}"
        stage_dir: "/tmp/sgrodocraft_{{ (latest_tag_file.content | b64decode).strip() }}"

#------------------------------------------#

  tasks:
    - name: stop minecraft
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: stopped
      ignore_errors: yes

    - name: create staging dir
      ansible.builtin.file:
        path: "{{ stage_dir }}"
        state: directory
        mode: "0755"

    - name: unarchive artifact to staging
      ansible.builtin.unarchive:
        src: "{{ artifacts_dir }}/config-{{ deploy_tag }}.zip"
        dest: "{{ stage_dir }}"
        remote_src: yes

    - name: set motd from tag
      when: set_motd_from_tag
      ansible.builtin.lineinfile:
        path: "{{ stage_dir }}/server.properties"
        regexp: '^motd='
        line: "motd=sgrodolcraft {{ deploy_tag }}"
        create: yes
        mode: "0644"

    - name: ensure base dirs exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: mc
        group: mc
        mode: "0755"
      loop:
        - "{{ target_dir }}/mods"
        - "{{ target_dir }}/plugins"

    - name: copy top files (no delete)
      ansible.builtin.shell: |
        set -e
        for f in server.properties run.sh user_jvm_args.txt; do
          [ -f "{{ stage_dir }}/$f" ] && cp -f "{{ stage_dir }}/$f" "{{ target_dir }}/$f" || true
        done
      args:
        executable: /bin/bash

    - name: sync mods jars only (delete jars, keep dirs)
      ansible.builtin.shell: >
        rsync -a --delete
        --include='*/' --include='*.jar' --exclude='*'
        "{{ stage_dir }}/mods/" "{{ target_dir }}/mods/" 2>/dev/null || true
      args:
        executable: /bin/bash

    - name: sync plugins jars only (delete jars, keep dirs)
      ansible.builtin.shell: >
        rsync -a --delete
        --include='*/' --include='*.jar' --exclude='*'
        "{{ stage_dir }}/plugins/" "{{ target_dir }}/plugins/" 2>/dev/null || true
      args:
        executable: /bin/bash

    - name: copy plugin configs (no delete)
      ansible.builtin.shell: >
        rsync -a --exclude='*.jar'
        "{{ stage_dir }}/plugins/" "{{ target_dir }}/plugins/" 2>/dev/null || true
      args:
        executable: /bin/bash

    - name: cleanup staging
      ansible.builtin.file:
        path: "{{ stage_dir }}"
        state: absent

    - name: fix ownership to mc
      ansible.builtin.file:
        path: "{{ target_dir }}"
        owner: mc
        group: mc
        recurse: yes

    - name: set default perms 755/644
      ansible.builtin.shell: |
        find "{{ target_dir }}" -type d -exec chmod 755 {} \;
        find "{{ target_dir }}" -type f -exec chmod 644 {} \;
      changed_when: false

    - name: ensure scripts executable
      ansible.builtin.shell: |
        [ -f "{{ target_dir }}/run.sh" ] && chmod 755 "{{ target_dir }}/run.sh" || true
        find "{{ target_dir }}" -type f -name '*.sh' -exec chmod 755 {} \;
      changed_when: false

    - name: start minecraft
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
        enabled: yes

    - name: health-check
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mc_port }}"
        delay: 2
        timeout: 60

    - name: save deployed tag marker
      ansible.builtin.copy:
        dest: "{{ target_dir }}/.last_good_commit"
        owner: mc
        group: mc
        mode: "0644"
        force: yes
        content: "{{ deploy_tag }}\n"

#------------------------------------------#

  post_tasks:
    - name: always clean staging
      ansible.builtin.file:
        path: "{{ stage_dir }}"
        state: absent
      ignore_errors: yes
