---
# rollback to the previous local artifact on mc
- name: rollback to previous build (local artifacts)
  hosts: mc_host
  become: yes
  become_user: root
  gather_facts: false

  vars:
    target_dir: /home/mc/minecraft-survival
    service_name: mc-survival-java
    mc_port: 25565
    artifacts_dir: "/srv/mc/artifacts"
    stage_dir: "/tmp/sgrodocraft_rollback"

  tasks:
    - name: read current deployed commit from target
      slurp:
        src: "{{ target_dir }}/.last_good_commit"
      register: current_sha_file
      failed_when: false

    - name: fail if current commit marker is missing
      fail:
        msg: "current commit marker not found; run a normal deploy first"
      when: current_sha_file.content is not defined

    - name: set current_sha fact
      set_fact:
        current_sha: "{{ (current_sha_file.content | b64decode).strip() }}"

    - name: compute previous sha on mc
      shell: |
        set -e
        cur="{{ current_sha }}"
        mapfile -t list < <(ls -1t {{ artifacts_dir }}/config-*.zip 2>/dev/null | sed -E 's|.*/config-([^.]+)\.zip|\1|')
        for i in "${!list[@]}"; do
          if [[ "${list[$i]}" == "$cur" ]]; then
            j=$((i+1))
            if [[ $j -lt ${#list[@]} ]]; then
              echo -n "${list[$j]}"
              exit 0
            fi
          fi
        done
        exit 1
      register: prev_sha_cmd
      changed_when: false

    - name: fail if there is no previous build
      fail:
        msg: "no previous artifact found for current sha {{ current_sha }}"
      when: prev_sha_cmd.rc != 0 or prev_sha_cmd.stdout | length == 0

    - name: set prev vars
      set_fact:
        prev_sha: "{{ prev_sha_cmd.stdout }}"
        prev_zip: "{{ artifacts_dir }}/config-{{ prev_sha }}.zip"

    - name: stop minecraft before rollback
      systemd: { name: "{{ service_name }}", state: stopped }
      ignore_errors: yes

    - name: create staging dir
      file: { path: "{{ stage_dir }}", state: directory, mode: "0755" }

    - name: unarchive previous artifact into staging
      unarchive:
        src: "{{ prev_zip }}"
        dest: "{{ stage_dir }}"
        remote_src: yes

    - name: rsync staging to target preserving state
      synchronize:
        src: "{{ stage_dir }}/"
        dest: "{{ target_dir }}/"
        archive: yes
        delete: no
        rsync_opts:
          - "--exclude=world/"
          - "--exclude=logs/"
          - "--exclude=crash-reports/"
          - "--exclude=*.lock"
          - "--exclude=eula.txt"
          - "--exclude=backups/"

    - name: cleanup staging
      file: { path: "{{ stage_dir }}", state: absent }

    - name: start minecraft after rollback
      systemd: { name: "{{ service_name }}", state: started, enabled: yes }

    - name: health-check
      wait_for: { host: 127.0.0.1, port: "{{ mc_port }}", delay: 2, timeout: 60 }

    - name: update marker to previous sha
      copy:
        content: "{{ prev_sha }}\n"
        dest: "{{ target_dir }}/.last_good_commit"
        owner: mc
        group: mc
        mode: "0644"